services:
  - type: web
    name: helpdesk-lite
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: helpdesk-db
          property: connectionString

databases:
  - name: helpdesk-db
    plan: free
    region: oregon
    databaseName: helpdesk_db
    user: helpdesk_user
